services:
  db:
    image: postgres:16.2
    container_name: postgres-db-vectorizer
    environment:
      POSTGRES_DB: vectorizer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "2345:5432"
volumes:
  db-data:
        